name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            echo "Pulling latest Docker images..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }} /nginx:${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }} /frontend:${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }} /backend:${{ github.sha }}

            echo "Stopping old containers..."
            docker compose down

            echo "Starting new containers..."
            docker compose up -d

            echo "Reloading Nginx configuration..."
            sudo systemctl restart nginx
